@startuml
interface dialogo{}

class dialogoMac implements  dialogo{}

class dioloWindows implements  dialogo{}

interface fabricaDialogo{}

class fabricaDialogoMac implements  fabricaDialogo{}

class fabricaDioloWindows implements  fabricaDialogo{}
@enduml

https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuShCAqajIajCJbL8oKpCoK_FhwxbuahEIImkXWdu9YOhPEOMvAJcfkQL52jWKvUVan-UcPUINrwCIoN2chJ4fABCv4GND5FWubWj9QmBuGJy-XnIyrA0_WO0
